# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.12.11                 # https://pyreadiness.org/3.10
  - uv=0.9.18                      # https://github.com/astral-sh/uv
  - openjdk=25.0.1               # https://adoptium.net/temurin/releases/?version=17
  - pip:
    - rpaframework==31.1.0        # https://rpaframework.org/releasenotes.html
    - robocorp==3.0.0             # https://pypi.org/project/robocorp
    - robocorp-browser==2.3.5     # https://pypi.org/project/robocorp-browser
    - robocorp-windows==1.0.4   # https://pypi.org/project/robocorp-windows
    - robocorp-tasks
    - rpaframework-recognition==7.0.1  # https://pypi.org/project/rpaframework-recognition
    - pywin32==311               # https://pypi.org/project/pywin32